checks:
    php:
        fix_use_statements:
            order_alphabetically: true
tools:
    php_code_sniffer:
        config:
            standard: PSR2
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
