language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install -o
  - php artisan config:cache
  - php artisan route:cache
  - php artisan alex:scan-posts

script: vendor/bin/phpunit
